### ISSUE TITLE
style /posts page

### ISSUE THREAD

**Issue by tykervella** [Ally27/Music-to-My-Ears#54]

**Comment by tykervella** [comment]
posts.handlebar

**Comment by terrinmack** [comment]
![image](https://user-images.githubusercontent.com/119826543/232281297-16578dec-9d6a-4cbf-9442-b46cd2810554.png)

**Comment by terrinmack** [comment]
![image](https://user-images.githubusercontent.com/119826543/232281560-1f1851b0-a754-4fc7-b18b-7e1e125d1d84.png)
Might need more formatting since theres nothing on the right hand side of the page
