### ISSUE TITLE
style /users page

### ISSUE THREAD

**Issue by tykervella** [Ally27/Music-to-My-Ears#57]
users.handlebars

**Comment by terrinmack** [comment]
/User
![image](https://user-images.githubusercontent.com/119826543/232283396-ef5f2912-cba7-4d90-9e6c-b942a992ba16.png)

**Comment by terrinmack** [comment]
/users
![image](https://user-images.githubusercontent.com/119826543/232284033-304cddcf-5664-438a-8bc6-2f4253a72d6a.png)

**Comment by tykervella** [comment]
Added rendering of images and fixed functionality of "Go to User" button
